/*
 * File:           C:\Users\Wei\Dropbox\Coding\notebooks\專案\待處理\SigmaDSP\bitbucket\github\SigmaStudio\projects\test\Design 1_IC_1_PARAM.h
 *
 * Created:        Sunday, February 27, 2022 6:19:52 AM
 * Description:    Design 1:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2022 Analog Devices, Inc. All rights reserved.
 */
#ifndef __DESIGN_1_IC_1_PARAM_H__
#define __DESIGN_1_IC_1_PARAM_H__


/* Module W Noise1 - White Noise*/
#define MOD_WNOISE1_COUNT                              3
#define MOD_WNOISE1_DEVICE                             "IC1"
#define MOD_WNOISE1_ALG0_ENABLENOISE_ADDR              0
#define MOD_WNOISE1_ALG0_ENABLENOISE_FIXPT             0x00000000
#define MOD_WNOISE1_ALG0_ENABLENOISE_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_WNOISE1_ALG0_ENABLENOISE_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_WNOISE1_ALG0_SEED_ADDR                     1
#define MOD_WNOISE1_ALG0_SEED_FIXPT                    0x0005464B
#define MOD_WNOISE1_ALG0_SEED_VALUE                    SIGMASTUDIOTYPE_INTEGER_CONVERT(345675)
#define MOD_WNOISE1_ALG0_SEED_TYPE                     SIGMASTUDIOTYPE_INTEGER
#define MOD_WNOISE1_ALG0_SEED_ADDR                     1
#define MOD_WNOISE1_ALG0_SEED_FIXPT                    0x0005464B
#define MOD_WNOISE1_ALG0_SEED_VALUE                    SIGMASTUDIOTYPE_INTEGER_CONVERT(345675)
#define MOD_WNOISE1_ALG0_SEED_TYPE                     SIGMASTUDIOTYPE_INTEGER

/* Module DC1 - DC Input Entry*/
#define MOD_DC1_COUNT                                  1
#define MOD_DC1_DEVICE                                 "IC1"
#define MOD_DC1_DCINPALG1_ADDR                         2
#define MOD_DC1_DCINPALG1_FIXPT                        0x01000000
#define MOD_DC1_DCINPALG1_VALUE                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2)
#define MOD_DC1_DCINPALG1_TYPE                         SIGMASTUDIOTYPE_FIXPOINT

/* Module Nx1-1_2 - Mono Switch Nx1*/
#define MOD_NX1_1_2_COUNT                              3
#define MOD_NX1_1_2_DEVICE                             "IC1"
#define MOD_NX1_1_2_ALG0_STAGE0_MONOSWITCHNOSLEW_ADDR  3
#define MOD_NX1_1_2_ALG0_STAGE0_MONOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_NX1_1_2_ALG0_STAGE0_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_NX1_1_2_ALG0_STAGE0_MONOSWITCHNOSLEW_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_NX1_1_2_ALG0_STAGE1_MONOSWITCHNOSLEW_ADDR  4
#define MOD_NX1_1_2_ALG0_STAGE1_MONOSWITCHNOSLEW_FIXPT 0x00800000
#define MOD_NX1_1_2_ALG0_STAGE1_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_NX1_1_2_ALG0_STAGE1_MONOSWITCHNOSLEW_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_NX1_1_2_ALG0_STAGE2_MONOSWITCHNOSLEW_ADDR  5
#define MOD_NX1_1_2_ALG0_STAGE2_MONOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_NX1_1_2_ALG0_STAGE2_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_NX1_1_2_ALG0_STAGE2_MONOSWITCHNOSLEW_TYPE  SIGMASTUDIOTYPE_FIXPOINT

/* Module Mute1 - Mute*/
#define MOD_MUTE1_COUNT                                2
#define MOD_MUTE1_DEVICE                               "IC1"
#define MOD_MUTE1_ALG0_MUTEONOFF_ADDR                  6
#define MOD_MUTE1_ALG0_MUTEONOFF_FIXPT                 0x00800000
#define MOD_MUTE1_ALG0_MUTEONOFF_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MUTE1_ALG0_MUTEONOFF_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MUTE1_ALG0_STEP_ADDR                       7
#define MOD_MUTE1_ALG0_STEP_FIXPT                      0x00002000
#define MOD_MUTE1_ALG0_STEP_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0009765625)
#define MOD_MUTE1_ALG0_STEP_TYPE                       SIGMASTUDIOTYPE_FIXPOINT

/* Module Gain1 - Gain*/
#define MOD_GAIN1_COUNT                                1
#define MOD_GAIN1_DEVICE                               "IC1"
#define MOD_GAIN1_GAIN1940ALGNS1_ADDR                  8
#define MOD_GAIN1_GAIN1940ALGNS1_FIXPT                 0x00800000
#define MOD_GAIN1_GAIN1940ALGNS1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_GAIN1_GAIN1940ALGNS1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module FIR1 - FIR Filter*/
#define MOD_FIR1_COUNT                                 11
#define MOD_FIR1_DEVICE                                "IC1"
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF00_ADDR       9
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF00_FIXPT      0x00800000
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF00_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF00_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF01_ADDR       10
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF01_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF01_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF01_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF02_ADDR       11
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF02_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF02_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF02_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF03_ADDR       12
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF03_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF03_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF03_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF04_ADDR       13
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF04_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF04_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF04_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF05_ADDR       14
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF05_FIXPT      0x00800000
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF05_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF05_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF06_ADDR       15
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF06_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF06_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF06_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF07_ADDR       16
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF07_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF07_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF07_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF08_ADDR       17
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF08_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF08_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF08_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF09_ADDR       18
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF09_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF09_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF09_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF010_ADDR      19
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF010_FIXPT     0x00800000
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF010_VALUE     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_FIR1_ALG0_FIRFILTALG1FIRCOEFF010_TYPE      SIGMASTUDIOTYPE_FIXPOINT

/* Module Compressor1 - RMS Detect (no:gain,hold,decay)*/
#define MOD_COMPRESSOR1_COUNT                          35
#define MOD_COMPRESSOR1_DEVICE                         "IC1"
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY10_ADDR 20
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY10_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY10_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY10_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY11_ADDR 21
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY11_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY11_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY11_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY12_ADDR 22
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY12_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY12_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY12_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY13_ADDR 23
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY13_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY13_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY13_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY14_ADDR 24
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY14_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY14_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY14_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY15_ADDR 25
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY15_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY15_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY15_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY16_ADDR 26
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY16_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY16_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY16_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY17_ADDR 27
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY17_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY17_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY17_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY18_ADDR 28
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY18_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY18_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY18_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY19_ADDR 29
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY19_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY19_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY19_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY110_ADDR 30
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY110_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY110_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY110_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY111_ADDR 31
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY111_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY111_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY111_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY112_ADDR 32
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY112_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY112_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY112_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY113_ADDR 33
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY113_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY113_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY113_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY114_ADDR 34
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY114_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY114_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY114_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY115_ADDR 35
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY115_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY115_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY115_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY116_ADDR 36
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY116_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY116_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY116_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY117_ADDR 37
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY117_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY117_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY117_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY118_ADDR 38
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY118_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY118_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY118_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY119_ADDR 39
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY119_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY119_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY119_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY120_ADDR 40
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY120_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY120_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY120_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY121_ADDR 41
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY121_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY121_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY121_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY122_ADDR 42
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY122_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY122_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY122_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY123_ADDR 43
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY123_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY123_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY123_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY124_ADDR 44
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY124_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY124_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY124_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY125_ADDR 45
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY125_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY125_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY125_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY126_ADDR 46
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY126_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY126_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY126_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY127_ADDR 47
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY127_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY127_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY127_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY128_ADDR 48
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY128_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY128_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY128_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY129_ADDR 49
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY129_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY129_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY129_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY130_ADDR 50
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY130_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY130_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY130_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY131_ADDR 51
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY131_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY131_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY131_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY132_ADDR 52
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY132_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY132_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY132_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY133_ADDR 53
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY133_FIXPT 0x00800000
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY133_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY133_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY1RMS_ADDR 54
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY1RMS_FIXPT 0x000012DE
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY1RMS_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000575811989360853)
#define MOD_COMPRESSOR1_ALG0_MONONOPOSTGAINNOHOLDNODELAY1RMS_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Nx2-1 - Stereo Switch Nx2*/
#define MOD_NX2_1_COUNT                                1
#define MOD_NX2_1_DEVICE                               "IC1"
#define MOD_NX2_1_STEREOSWSLEW_ADDR                    55
#define MOD_NX2_1_STEREOSWSLEW_FIXPT                   0x00000000
#define MOD_NX2_1_STEREOSWSLEW_VALUE                   SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_NX2_1_STEREOSWSLEW_TYPE                    SIGMASTUDIOTYPE_INTEGER

/* Module Nx1-2 - Mono Switch Nx1*/
#define MOD_NX1_2_COUNT                                3
#define MOD_NX1_2_DEVICE                               "IC1"
#define MOD_NX1_2_ALG0_STAGE0_MONOSWITCHNOSLEW_ADDR    56
#define MOD_NX1_2_ALG0_STAGE0_MONOSWITCHNOSLEW_FIXPT   0x00800000
#define MOD_NX1_2_ALG0_STAGE0_MONOSWITCHNOSLEW_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_NX1_2_ALG0_STAGE0_MONOSWITCHNOSLEW_TYPE    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_NX1_2_ALG0_STAGE1_MONOSWITCHNOSLEW_ADDR    57
#define MOD_NX1_2_ALG0_STAGE1_MONOSWITCHNOSLEW_FIXPT   0x00000000
#define MOD_NX1_2_ALG0_STAGE1_MONOSWITCHNOSLEW_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_NX1_2_ALG0_STAGE1_MONOSWITCHNOSLEW_TYPE    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_NX1_2_ALG0_STAGE2_MONOSWITCHNOSLEW_ADDR    58
#define MOD_NX1_2_ALG0_STAGE2_MONOSWITCHNOSLEW_FIXPT   0x00000000
#define MOD_NX1_2_ALG0_STAGE2_MONOSWITCHNOSLEW_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_NX1_2_ALG0_STAGE2_MONOSWITCHNOSLEW_TYPE    SIGMASTUDIOTYPE_FIXPOINT

/* Module Nx1-1 - Mono Switch Nx1*/
#define MOD_NX1_1_COUNT                                3
#define MOD_NX1_1_DEVICE                               "IC1"
#define MOD_NX1_1_ALG0_STAGE0_MONOSWITCHNOSLEW_ADDR    59
#define MOD_NX1_1_ALG0_STAGE0_MONOSWITCHNOSLEW_FIXPT   0x00800000
#define MOD_NX1_1_ALG0_STAGE0_MONOSWITCHNOSLEW_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_NX1_1_ALG0_STAGE0_MONOSWITCHNOSLEW_TYPE    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_NX1_1_ALG0_STAGE1_MONOSWITCHNOSLEW_ADDR    60
#define MOD_NX1_1_ALG0_STAGE1_MONOSWITCHNOSLEW_FIXPT   0x00000000
#define MOD_NX1_1_ALG0_STAGE1_MONOSWITCHNOSLEW_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_NX1_1_ALG0_STAGE1_MONOSWITCHNOSLEW_TYPE    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_NX1_1_ALG0_STAGE2_MONOSWITCHNOSLEW_ADDR    61
#define MOD_NX1_1_ALG0_STAGE2_MONOSWITCHNOSLEW_FIXPT   0x00000000
#define MOD_NX1_1_ALG0_STAGE2_MONOSWITCHNOSLEW_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_NX1_1_ALG0_STAGE2_MONOSWITCHNOSLEW_TYPE    SIGMASTUDIOTYPE_FIXPOINT

/* Module SW vol 1 - Single SW slew vol (adjustable)*/
#define MOD_SWVOL1_COUNT                               2
#define MOD_SWVOL1_DEVICE                              "IC1"
#define MOD_SWVOL1_ALG0_TARGET_ADDR                    62
#define MOD_SWVOL1_ALG0_TARGET_FIXPT                   0x000AA586
#define MOD_SWVOL1_ALG0_TARGET_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0831763771102672)
#define MOD_SWVOL1_ALG0_TARGET_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SWVOL1_ALG0_STEP_ADDR                      63
#define MOD_SWVOL1_ALG0_STEP_FIXPT                     0x00000100
#define MOD_SWVOL1_ALG0_STEP_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.0517578125E-05)
#define MOD_SWVOL1_ALG0_STEP_TYPE                      SIGMASTUDIOTYPE_FIXPOINT

#endif
