/*
 * File:           C:\Users\Wei\Dropbox\Coding\notebooks\專案\待處理\SigmaDSP\bitbucket\github\SigmaStudio projects\projects\test\Design 1_IC_1_PARAM.h
 *
 * Created:        Tuesday, March 8, 2022 10:18:00 AM
 * Description:    Design 1:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2022 Analog Devices, Inc. All rights reserved.
 */
#ifndef __DESIGN_1_IC_1_PARAM_H__
#define __DESIGN_1_IC_1_PARAM_H__


/* Module Tone1 - Sine Tone*/
#define MOD_TONE1_COUNT                                3
#define MOD_TONE1_DEVICE                               "IC1"
#define MOD_STATIC_TONE1_ALG0_MASK_ADDR                0
#define MOD_STATIC_TONE1_ALG0_MASK_FIXPT               0x000000FF
#define MOD_STATIC_TONE1_ALG0_MASK_VALUE               SIGMASTUDIOTYPE_INTEGER_CONVERT(255)
#define MOD_STATIC_TONE1_ALG0_MASK_TYPE                SIGMASTUDIOTYPE_INTEGER
#define MOD_TONE1_ALG0_INCREMENT_ADDR                  1
#define MOD_TONE1_ALG0_INCREMENT_FIXPT                 0x0000962F
#define MOD_TONE1_ALG0_INCREMENT_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00458333333333333)
#define MOD_TONE1_ALG0_INCREMENT_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TONE1_ALG0_ON_ADDR                         2
#define MOD_TONE1_ALG0_ON_FIXPT                        0x00800000
#define MOD_TONE1_ALG0_ON_VALUE                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_TONE1_ALG0_ON_TYPE                         SIGMASTUDIOTYPE_FIXPOINT

/* Module Tone2 - Sine Tone*/
#define MOD_TONE2_COUNT                                3
#define MOD_TONE2_DEVICE                               "IC1"
#define MOD_STATIC_TONE2_ALG0_MASK_ADDR                3
#define MOD_STATIC_TONE2_ALG0_MASK_FIXPT               0x000000FF
#define MOD_STATIC_TONE2_ALG0_MASK_VALUE               SIGMASTUDIOTYPE_INTEGER_CONVERT(255)
#define MOD_STATIC_TONE2_ALG0_MASK_TYPE                SIGMASTUDIOTYPE_INTEGER
#define MOD_TONE2_ALG0_INCREMENT_ADDR                  4
#define MOD_TONE2_ALG0_INCREMENT_FIXPT                 0x00009BA5
#define MOD_TONE2_ALG0_INCREMENT_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00475)
#define MOD_TONE2_ALG0_INCREMENT_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TONE2_ALG0_ON_ADDR                         5
#define MOD_TONE2_ALG0_ON_FIXPT                        0x00800000
#define MOD_TONE2_ALG0_ON_VALUE                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_TONE2_ALG0_ON_TYPE                         SIGMASTUDIOTYPE_FIXPOINT

/* Module White_Noise - White Noise*/
#define MOD_WHITE_NOISE_COUNT                          3
#define MOD_WHITE_NOISE_DEVICE                         "IC1"
#define MOD_WHITE_NOISE_ALG0_ENABLENOISE_ADDR          6
#define MOD_WHITE_NOISE_ALG0_ENABLENOISE_FIXPT         0x00800000
#define MOD_WHITE_NOISE_ALG0_ENABLENOISE_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_WHITE_NOISE_ALG0_ENABLENOISE_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_WHITE_NOISE_ALG0_SEED_ADDR                 7
#define MOD_WHITE_NOISE_ALG0_SEED_FIXPT                0x0005464B
#define MOD_WHITE_NOISE_ALG0_SEED_VALUE                SIGMASTUDIOTYPE_INTEGER_CONVERT(345675)
#define MOD_WHITE_NOISE_ALG0_SEED_TYPE                 SIGMASTUDIOTYPE_INTEGER
#define MOD_WHITE_NOISE_ALG0_SEED_ADDR                 7
#define MOD_WHITE_NOISE_ALG0_SEED_FIXPT                0x0005464B
#define MOD_WHITE_NOISE_ALG0_SEED_VALUE                SIGMASTUDIOTYPE_INTEGER_CONVERT(345675)
#define MOD_WHITE_NOISE_ALG0_SEED_TYPE                 SIGMASTUDIOTYPE_INTEGER

/* Module Source_Switch_0 - Stereo Switch Nx2*/
#define MOD_SOURCE_SWITCH_0_COUNT                      1
#define MOD_SOURCE_SWITCH_0_DEVICE                     "IC1"
#define MOD_SOURCE_SWITCH_0_STEREOSWSLEW_ADDR          8
#define MOD_SOURCE_SWITCH_0_STEREOSWSLEW_FIXPT         0x00000000
#define MOD_SOURCE_SWITCH_0_STEREOSWSLEW_VALUE         SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_SOURCE_SWITCH_0_STEREOSWSLEW_TYPE          SIGMASTUDIOTYPE_INTEGER

/* Module Mute_in0 - Mute*/
#define MOD_MUTE_IN0_COUNT                             1
#define MOD_MUTE_IN0_DEVICE                            "IC1"
#define MOD_MUTE_IN0_MUTENOSLEWALG13MUTE_ADDR          9
#define MOD_MUTE_IN0_MUTENOSLEWALG13MUTE_FIXPT         0x00800000
#define MOD_MUTE_IN0_MUTENOSLEWALG13MUTE_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MUTE_IN0_MUTENOSLEWALG13MUTE_TYPE          SIGMASTUDIOTYPE_FIXPOINT

/* Module Mute_in1 - Mute*/
#define MOD_MUTE_IN1_COUNT                             1
#define MOD_MUTE_IN1_DEVICE                            "IC1"
#define MOD_MUTE_IN1_MUTENOSLEWALG14MUTE_ADDR          10
#define MOD_MUTE_IN1_MUTENOSLEWALG14MUTE_FIXPT         0x00800000
#define MOD_MUTE_IN1_MUTENOSLEWALG14MUTE_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MUTE_IN1_MUTENOSLEWALG14MUTE_TYPE          SIGMASTUDIOTYPE_FIXPOINT

/* Module Gain_in0 - Gain*/
#define MOD_GAIN_IN0_COUNT                             1
#define MOD_GAIN_IN0_DEVICE                            "IC1"
#define MOD_GAIN_IN0_GAIN1940ALGNS2_ADDR               11
#define MOD_GAIN_IN0_GAIN1940ALGNS2_FIXPT              0x00800000
#define MOD_GAIN_IN0_GAIN1940ALGNS2_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_GAIN_IN0_GAIN1940ALGNS2_TYPE               SIGMASTUDIOTYPE_FIXPOINT

/* Module Gain_in1 - Gain*/
#define MOD_GAIN_IN1_COUNT                             1
#define MOD_GAIN_IN1_DEVICE                            "IC1"
#define MOD_GAIN_IN1_GAIN1940ALGNS3_ADDR               12
#define MOD_GAIN_IN1_GAIN1940ALGNS3_FIXPT              0x00800000
#define MOD_GAIN_IN1_GAIN1940ALGNS3_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_GAIN_IN1_GAIN1940ALGNS3_TYPE               SIGMASTUDIOTYPE_FIXPOINT

/* Module FIR0 - FIR Filter*/
#define MOD_FIR0_COUNT                                 10
#define MOD_FIR0_DEVICE                                "IC1"
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF00_ADDR       13
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF00_FIXPT      0x00800000
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF00_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF00_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF01_ADDR       14
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF01_FIXPT      0x00000000
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF01_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF01_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF02_ADDR       15
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF02_FIXPT      0x00000000
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF02_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF02_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF03_ADDR       16
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF03_FIXPT      0x00000000
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF03_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF03_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF04_ADDR       17
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF04_FIXPT      0x00000000
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF04_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF04_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF05_ADDR       18
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF05_FIXPT      0x00000000
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF05_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF05_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF06_ADDR       19
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF06_FIXPT      0x00000000
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF06_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF06_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF07_ADDR       20
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF07_FIXPT      0x00000000
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF07_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF07_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF08_ADDR       21
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF08_FIXPT      0x00000000
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF08_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF08_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF09_ADDR       22
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF09_FIXPT      0x00000000
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF09_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR0_ALG0_FIRFILTALG1FIRCOEFF09_TYPE       SIGMASTUDIOTYPE_FIXPOINT

/* Module FIR1 - FIR Filter*/
#define MOD_FIR1_COUNT                                 10
#define MOD_FIR1_DEVICE                                "IC1"
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF00_ADDR       23
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF00_FIXPT      0x00800000
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF00_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF00_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF01_ADDR       24
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF01_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF01_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF01_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF02_ADDR       25
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF02_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF02_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF02_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF03_ADDR       26
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF03_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF03_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF03_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF04_ADDR       27
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF04_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF04_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF04_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF05_ADDR       28
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF05_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF05_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF05_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF06_ADDR       29
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF06_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF06_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF06_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF07_ADDR       30
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF07_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF07_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF07_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF08_ADDR       31
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF08_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF08_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF08_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF09_ADDR       32
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF09_FIXPT      0x00000000
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF09_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_FIR1_ALG0_FIRFILTALG2FIRCOEFF09_TYPE       SIGMASTUDIOTYPE_FIXPOINT

#endif
